#!/usr/bin/env bash

LABEL=$(date +%Y%m%dT%H%M%S)-start

for s in mac mac-data
do
    zfs snapshot z/images/${s}@${LABEL}
done

if [ -f /tmp/mac-ephemeral.img ]
then
    exit 0;
fi

truncate -s 64G /tmp/mac-ephemeral.img
DEVICE=$(losetup -f --show /tmp/mac-ephemeral.img)
parted ${DEVICE} mklabel gpt
parted ${DEVICE} mkpart primary hfs+ 1 100%
mkfs.hfs -v Ephemeral ${DEVICE}p1
mkdir -p /tmp/mac-ephemeral
mount ${DEVICE}p1 /tmp/mac-ephemeral
#mkdir -p /tmp/mac-ephemeral/build
#mkdir -p /tmp/mac-ephemeral/build/loom-native
#mkdir -p /tmp/mac-ephemeral/build/loom-native-2
#mkdir -p /tmp/mac-ephemeral/clion
#mkdir -p /tmp/mac-ephemeral/clion/loom-native
#mkdir -p /tmp/mac-ephemeral/clion/loom-native-2
chmod -R 777 /tmp/mac-ephemeral
umount /tmp/mac-ephemeral
losetup -d ${DEVICE}
