#!/bin/sh
version="${1}"
# passing the kernel version is required
[ -z "${version}" ] && exit 0
echo "Fixing up boot links for ${version}"
cd /boot
ln -sf vmlinuz-${version} vmlinuz-debian
touch initrd.img-${version} # In case it doesn't exist yet
ln -sf initrd.img-${version} initrd.img-debian
