#!/bin/sh
version="${1}"
# passing the kernel version is required
[ -z "${version}" ] && exit 0

echo "Fixing up boot entry for ${version}"
sed -i "s|^linux*$|linux   /vmlinuz-${version}|g" /boot/loader/entries/ubuntu.conf
sed -i "s|^initrd*$|initrd  /initrd.img-${version}|g" /boot/loader/entries/ubuntu.conf
