#!/usr/bin/env bash

LABEL=$(date +%Y%m%dT%H%M%S)-start

rsync -arP --delete /etc/libvirt/hooks/ /var/lib/libvirt/images/hooks
for i in $( virsh list --name --all )
do
    virsh dumpxml ${i} >/var/lib/libvirt/images/${i}.xml
done
zfs snapshot z/images@${LABEL}
